# Generated by Django 4.2.5 on 2023-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Excel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("excel", models.FileField(upload_to="uploaded_excels/")),
                ("a1", models.CharField(max_length=30)),
                ("b1", models.CharField(max_length=30)),
                ("c1", models.CharField(max_length=30)),
                ("d1", models.CharField(max_length=30)),
                ("e1", models.CharField(max_length=30)),
                ("a2", models.CharField(max_length=30)),
                ("b2", models.CharField(max_length=30)),
                ("c2", models.CharField(max_length=30)),
                ("d2", models.CharField(max_length=30)),
                ("e2", models.CharField(max_length=30)),
                ("a3", models.CharField(max_length=30)),
                ("b3", models.CharField(max_length=30)),
                ("c3", models.CharField(max_length=30)),
                ("d3", models.CharField(max_length=30)),
                ("e3", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="uploaded_images/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
