# Generated by Django 4.2.5 on 2023-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excel",
            name="a1",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="a2",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="a3",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b1",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b2",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b3",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c1",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c2",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c3",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d1",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d2",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d3",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e1",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e2",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e3",
            field=models.CharField(default="", max_length=30),
        ),
    ]
