# Generated by Django 4.2.5 on 2023-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0002_alter_excel_a1_alter_excel_a2_alter_excel_a3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excel",
            name="a1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="a2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="a3",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="b3",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="c3",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="d3",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="excel",
            name="e3",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
